### ISSUE TITLE
Bruh pls give your telegram username

### ISSUE THREAD

**Issue by Sushrut1101** [Imshubh69/dragoon_kernel#2]
Hey!
Please give your new telegram username

Need some help from you asap

**Comment by Imshubh69** [comment]
> Hey! Please give your new telegram username
> 
> Need some help from you asap

I am ain't using telegram anymore

**Comment by Sushrut1101** [comment]
> > Hey! Please give your new telegram username
> > Need some help from you asap
> 
> I am ain't using telegram anymore

Bruh, then how to contact you?
Discord ??

**Comment by Imshubh69** [comment]
> > > Hey! Please give your new telegram username
> > > Need some help from you asap
> > 
> > 
> > I am ain't using telegram anymore
> 
> Bruh, then how to contact you? Discord ??


Insta

https://www.instagram.com/imshubh289/

**Comment by Imshubh69** [comment]
> > > Hey! Please give your new telegram username
> > > Need some help from you asap
> > 
> > 
> > I am ain't using telegram anymore
> 
> Bruh, then how to contact you? Discord ??

Bro are you dead?

**Comment by Sushrut1101** [comment]
> > > > Hey! Please give your new telegram username
> > > > Need some help from you asap
> > > 
> > > 
> > > I am ain't using telegram anymore
> > 
> > 
> > Bruh, then how to contact you? Discord ??
> 
> Insta
> 
> https://www.instagram.com/imshubh289/

Ohhk thanks

**Comment by Imshubh69** [comment]
> > > > > Hey! Please give your new telegram username
> > > > > Need some help from you asap
> > > > 
> > > > 
> > > > I am ain't using telegram anymore
> > > 
> > > 
> > > Bruh, then how to contact you? Discord ??
> > 
> > 
> > Insta
> > https://www.instagram.com/imshubh289/
> 
> Ohhk thanks

Well i also don't use insta anymore xD

**Comment by Sushrut1101** [comment]
> > > > > > Hey! Please give your new telegram username
> > > > > > Need some help from you asap
> > > > > 
> > > > > 
> > > > > I am ain't using telegram anymore
> > > > 
> > > > 
> > > > Bruh, then how to contact you? Discord ??
> > > 
> > > 
> > > Insta
> > > https://www.instagram.com/imshubh289/
> > 
> > 
> > Ohhk thanks
> 
> Well i also don't use insta anymore xD

What?? Then how to contact you ?

**Comment by Imshubh69** [comment]
> > > > > > > Hey! Please give your new telegram username
> > > > > > > Need some help from you asap
> > > > > > 
> > > > > > 
> > > > > > I am ain't using telegram anymore
> > > > > 
> > > > > 
> > > > > Bruh, then how to contact you? Discord ??
> > > > 
> > > > 
> > > > Insta
> > > > https://www.instagram.com/imshubh289/
> > > 
> > > 
> > > Ohhk thanks
> > 
> > 
> > Well i also don't use insta anymore xD
> 
> What?? Then how to contact you ?

well you mailed you at your email address guptasushrut@gmail.com check it out or either mail me on vishwajitg471@gmail.com

**Comment by Imshubh69** [comment]
I am closing this issue because it seems like your are inactive
